"""Create deterministic CPU controls and baseline fingerprints. No production execution."""
import json
import subprocess
from pathlib import Path

import cv2
import numpy as np

from lab.core import ROOT, digest, source_files, now


def make_case(base, variant='static', frames=12):
    folder = base / variant
    if (folder / 'case.json').exists():
        return folder / 'case.json'
    for name in ('input', 'mask', 'ground_truth'):
        (folder / name).mkdir(parents=True, exist_ok=True)
    for i in range(frames):
        y, x = np.indices((96, 160))
        shift = i * 2 if variant == 'pan' else 0
        gt = np.stack([((x + shift)*2) % 256, (y*2) % 256, (x+y) % 256], -1).astype(np.uint8)
        if variant == 'scene-cut' and i >= frames // 2:
            gt = 255 - gt
        mask = np.zeros(gt.shape[:2], np.uint8)
        cv2.putText(mask, 'TEST', (32, 72), cv2.FONT_HERSHEY_SIMPLEX, .65, 255, 2, cv2.LINE_8)
        frame = gt.copy()
        frame[mask > 0] = 255
        for key, data in [('input', frame), ('mask', mask), ('ground_truth', gt)]:
            if not cv2.imwrite(str(folder / key / f'{i:06}.png'), data):
                raise RuntimeError('PNG write failed')
    case = {'id': 'synthetic-' + variant, 'kind': 'synthetic-harness-control',
            'categories': [variant, 'white-subtitle'], 'fps': 30, 'frames': frames,
            'input': 'input', 'mask': 'mask', 'ground_truth': 'ground_truth',
            'scene_cuts': [frames // 2] if variant == 'scene-cut' else [],
            'rights': 'Procedurally generated by this repository; no external media',
            'generator': 'research/bootstrap.py::make_case; deterministic; no random seed needed'}
    file = folder / 'case.json'
    file.write_text(json.dumps(case, indent=2), encoding='utf-8')
    return file


def main():
    for variant in ('static', 'pan', 'scene-cut'):
        print(make_case(ROOT / 'research/benchmarks/data', variant).relative_to(ROOT))
    baseline = {'created_at': now(), 'kind': 'LOCAL_WORKING_TREE_NOT_DEPLOYMENT',
                'git_head': subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip(),
                'files': {p.relative_to(ROOT).as_posix(): digest(p) for p in source_files()}}
    path = ROOT / 'research/current-system/baseline.json'
    if not path.exists():
        path.write_text(json.dumps(baseline, indent=2), encoding='utf-8')
    print('Baseline fingerprint preserved:', path)


if __name__ == '__main__':
    main()
