/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ArmazenamentoRouteImport } from './routes/armazenamento'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as LimparIaRouteImport } from './routes/limpar-ia'
import { Route as LiveRouteImport } from './routes/live'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicCleanerCallbackRouteImport } from './routes/api/public/cleaner-callback'
import { Route as ApiPublicCleanerUploadRouteImport } from './routes/api/public/cleaner-upload'
import { Route as ApiPublicHlsProxyRouteImport } from './routes/api/public/hls-proxy'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'
import { Route as ApiPublicRenderHookRouteImport } from './routes/api/public/render-hook'
import { Route as ApiPublicRenderUploadRouteImport } from './routes/api/public/render-upload'
import { Route as IntegracoesFacebookCallbackRouteImport } from './routes/integracoes_.facebook.callback'
import { Route as IntegracoesInstagramCallbackRouteImport } from './routes/integracoes_.instagram.callback'
import { Route as IntegracoesTiktokCallbackRouteImport } from './routes/integracoes_.tiktok.callback'
import { Route as IntegracoesYoutubeCallbackRouteImport } from './routes/integracoes_.youtube.callback'
import { Route as ApiPublicHooksPublishDueRouteImport } from './routes/api/public/hooks/publish-due'
import { Route as ApiPublicMetaDataDeletionRouteImport } from './routes/api/public/meta.data-deletion'
import { Route as ApiPublicMetaDeauthorizeRouteImport } from './routes/api/public/meta.deauthorize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmazenamentoRoute = ArmazenamentoRouteImport.update({
  id: '/armazenamento',
  path: '/armazenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LimparIaRoute = LimparIaRouteImport.update({
  id: '/limpar-ia',
  path: '/limpar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCleanerCallbackRoute =
  ApiPublicCleanerCallbackRouteImport.update({
    id: '/api/public/cleaner-callback',
    path: '/api/public/cleaner-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCleanerUploadRoute = ApiPublicCleanerUploadRouteImport.update({
  id: '/api/public/cleaner-upload',
  path: '/api/public/cleaner-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHlsProxyRoute = ApiPublicHlsProxyRouteImport.update({
  id: '/api/public/hls-proxy',
  path: '/api/public/hls-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderHookRoute = ApiPublicRenderHookRouteImport.update({
  id: '/api/public/render-hook',
  path: '/api/public/render-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderUploadRoute = ApiPublicRenderUploadRouteImport.update({
  id: '/api/public/render-upload',
  path: '/api/public/render-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesFacebookCallbackRoute =
  IntegracoesFacebookCallbackRouteImport.update({
    id: '/integracoes_/facebook/callback',
    path: '/integracoes/facebook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegracoesInstagramCallbackRoute =
  IntegracoesInstagramCallbackRouteImport.update({
    id: '/integracoes_/instagram/callback',
    path: '/integracoes/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegracoesTiktokCallbackRoute =
  IntegracoesTiktokCallbackRouteImport.update({
    id: '/integracoes_/tiktok/callback',
    path: '/integracoes/tiktok/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegracoesYoutubeCallbackRoute =
  IntegracoesYoutubeCallbackRouteImport.update({
    id: '/integracoes_/youtube/callback',
    path: '/integracoes/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPublishDueRoute =
  ApiPublicHooksPublishDueRouteImport.update({
    id: '/api/public/hooks/publish-due',
    path: '/api/public/hooks/publish-due',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaDataDeletionRoute =
  ApiPublicMetaDataDeletionRouteImport.update({
    id: '/api/public/meta/data-deletion',
    path: '/api/public/meta/data-deletion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaDeauthorizeRoute =
  ApiPublicMetaDeauthorizeRouteImport.update({
    id: '/api/public/meta/deauthorize',
    path: '/api/public/meta/deauthorize',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/fotos': typeof FotosRoute
  '/integracoes': typeof IntegracoesRoute
  '/limpar-ia': typeof LimparIaRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/metricas': typeof MetricasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cleaner-callback': typeof ApiPublicCleanerCallbackRoute
  '/api/public/cleaner-upload': typeof ApiPublicCleanerUploadRoute
  '/api/public/hls-proxy': typeof ApiPublicHlsProxyRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/render-hook': typeof ApiPublicRenderHookRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/integracoes/facebook/callback': typeof IntegracoesFacebookCallbackRoute
  '/integracoes/instagram/callback': typeof IntegracoesInstagramCallbackRoute
  '/integracoes/tiktok/callback': typeof IntegracoesTiktokCallbackRoute
  '/integracoes/youtube/callback': typeof IntegracoesYoutubeCallbackRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/fotos': typeof FotosRoute
  '/integracoes': typeof IntegracoesRoute
  '/limpar-ia': typeof LimparIaRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/metricas': typeof MetricasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cleaner-callback': typeof ApiPublicCleanerCallbackRoute
  '/api/public/cleaner-upload': typeof ApiPublicCleanerUploadRoute
  '/api/public/hls-proxy': typeof ApiPublicHlsProxyRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/render-hook': typeof ApiPublicRenderHookRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/integracoes/facebook/callback': typeof IntegracoesFacebookCallbackRoute
  '/integracoes/instagram/callback': typeof IntegracoesInstagramCallbackRoute
  '/integracoes/tiktok/callback': typeof IntegracoesTiktokCallbackRoute
  '/integracoes/youtube/callback': typeof IntegracoesYoutubeCallbackRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/fotos': typeof FotosRoute
  '/integracoes': typeof IntegracoesRoute
  '/limpar-ia': typeof LimparIaRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/metricas': typeof MetricasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/cleaner-callback': typeof ApiPublicCleanerCallbackRoute
  '/api/public/cleaner-upload': typeof ApiPublicCleanerUploadRoute
  '/api/public/hls-proxy': typeof ApiPublicHlsProxyRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/render-hook': typeof ApiPublicRenderHookRoute
  '/api/public/render-upload': typeof ApiPublicRenderUploadRoute
  '/integracoes_/facebook/callback': typeof IntegracoesFacebookCallbackRoute
  '/integracoes_/instagram/callback': typeof IntegracoesInstagramCallbackRoute
  '/integracoes_/tiktok/callback': typeof IntegracoesTiktokCallbackRoute
  '/integracoes_/youtube/callback': typeof IntegracoesYoutubeCallbackRoute
  '/api/public/hooks/publish-due': typeof ApiPublicHooksPublishDueRoute
  '/api/public/meta/data-deletion': typeof ApiPublicMetaDataDeletionRoute
  '/api/public/meta/deauthorize': typeof ApiPublicMetaDeauthorizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/armazenamento'
    | '/biblioteca'
    | '/checkout'
    | '/conta'
    | '/exclusao-de-dados'
    | '/fotos'
    | '/integracoes'
    | '/limpar-ia'
    | '/live'
    | '/mcp'
    | '/metricas'
    | '/privacidade'
    | '/termos'
    | '/vendas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cleaner-callback'
    | '/api/public/cleaner-upload'
    | '/api/public/hls-proxy'
    | '/api/public/media-proxy'
    | '/api/public/render-hook'
    | '/api/public/render-upload'
    | '/integracoes/facebook/callback'
    | '/integracoes/instagram/callback'
    | '/integracoes/tiktok/callback'
    | '/integracoes/youtube/callback'
    | '/api/public/hooks/publish-due'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/armazenamento'
    | '/biblioteca'
    | '/checkout'
    | '/conta'
    | '/exclusao-de-dados'
    | '/fotos'
    | '/integracoes'
    | '/limpar-ia'
    | '/live'
    | '/mcp'
    | '/metricas'
    | '/privacidade'
    | '/termos'
    | '/vendas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cleaner-callback'
    | '/api/public/cleaner-upload'
    | '/api/public/hls-proxy'
    | '/api/public/media-proxy'
    | '/api/public/render-hook'
    | '/api/public/render-upload'
    | '/integracoes/facebook/callback'
    | '/integracoes/instagram/callback'
    | '/integracoes/tiktok/callback'
    | '/integracoes/youtube/callback'
    | '/api/public/hooks/publish-due'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/armazenamento'
    | '/biblioteca'
    | '/checkout'
    | '/conta'
    | '/exclusao-de-dados'
    | '/fotos'
    | '/integracoes'
    | '/limpar-ia'
    | '/live'
    | '/mcp'
    | '/metricas'
    | '/privacidade'
    | '/termos'
    | '/vendas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/cleaner-callback'
    | '/api/public/cleaner-upload'
    | '/api/public/hls-proxy'
    | '/api/public/media-proxy'
    | '/api/public/render-hook'
    | '/api/public/render-upload'
    | '/integracoes_/facebook/callback'
    | '/integracoes_/instagram/callback'
    | '/integracoes_/tiktok/callback'
    | '/integracoes_/youtube/callback'
    | '/api/public/hooks/publish-due'
    | '/api/public/meta/data-deletion'
    | '/api/public/meta/deauthorize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  ArmazenamentoRoute: typeof ArmazenamentoRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  FotosRoute: typeof FotosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LimparIaRoute: typeof LimparIaRoute
  LiveRoute: typeof LiveRoute
  McpRoute: typeof McpRoute
  MetricasRoute: typeof MetricasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  VendasRoute: typeof VendasRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCleanerCallbackRoute: typeof ApiPublicCleanerCallbackRoute
  ApiPublicCleanerUploadRoute: typeof ApiPublicCleanerUploadRoute
  ApiPublicHlsProxyRoute: typeof ApiPublicHlsProxyRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicRenderHookRoute: typeof ApiPublicRenderHookRoute
  ApiPublicRenderUploadRoute: typeof ApiPublicRenderUploadRoute
  IntegracoesFacebookCallbackRoute: typeof IntegracoesFacebookCallbackRoute
  IntegracoesInstagramCallbackRoute: typeof IntegracoesInstagramCallbackRoute
  IntegracoesTiktokCallbackRoute: typeof IntegracoesTiktokCallbackRoute
  IntegracoesYoutubeCallbackRoute: typeof IntegracoesYoutubeCallbackRoute
  ApiPublicHooksPublishDueRoute: typeof ApiPublicHooksPublishDueRoute
  ApiPublicMetaDataDeletionRoute: typeof ApiPublicMetaDataDeletionRoute
  ApiPublicMetaDeauthorizeRoute: typeof ApiPublicMetaDeauthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armazenamento': {
      id: '/armazenamento'
      path: '/armazenamento'
      fullPath: '/armazenamento'
      preLoaderRoute: typeof ArmazenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpar-ia': {
      id: '/limpar-ia'
      path: '/limpar-ia'
      fullPath: '/limpar-ia'
      preLoaderRoute: typeof LimparIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleaner-callback': {
      id: '/api/public/cleaner-callback'
      path: '/api/public/cleaner-callback'
      fullPath: '/api/public/cleaner-callback'
      preLoaderRoute: typeof ApiPublicCleanerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleaner-upload': {
      id: '/api/public/cleaner-upload'
      path: '/api/public/cleaner-upload'
      fullPath: '/api/public/cleaner-upload'
      preLoaderRoute: typeof ApiPublicCleanerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hls-proxy': {
      id: '/api/public/hls-proxy'
      path: '/api/public/hls-proxy'
      fullPath: '/api/public/hls-proxy'
      preLoaderRoute: typeof ApiPublicHlsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-hook': {
      id: '/api/public/render-hook'
      path: '/api/public/render-hook'
      fullPath: '/api/public/render-hook'
      preLoaderRoute: typeof ApiPublicRenderHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-upload': {
      id: '/api/public/render-upload'
      path: '/api/public/render-upload'
      fullPath: '/api/public/render-upload'
      preLoaderRoute: typeof ApiPublicRenderUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/facebook/callback': {
      id: '/integracoes_/facebook/callback'
      path: '/integracoes/facebook/callback'
      fullPath: '/integracoes/facebook/callback'
      preLoaderRoute: typeof IntegracoesFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/instagram/callback': {
      id: '/integracoes_/instagram/callback'
      path: '/integracoes/instagram/callback'
      fullPath: '/integracoes/instagram/callback'
      preLoaderRoute: typeof IntegracoesInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/tiktok/callback': {
      id: '/integracoes_/tiktok/callback'
      path: '/integracoes/tiktok/callback'
      fullPath: '/integracoes/tiktok/callback'
      preLoaderRoute: typeof IntegracoesTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes_/youtube/callback': {
      id: '/integracoes_/youtube/callback'
      path: '/integracoes/youtube/callback'
      fullPath: '/integracoes/youtube/callback'
      preLoaderRoute: typeof IntegracoesYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-due': {
      id: '/api/public/hooks/publish-due'
      path: '/api/public/hooks/publish-due'
      fullPath: '/api/public/hooks/publish-due'
      preLoaderRoute: typeof ApiPublicHooksPublishDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/data-deletion': {
      id: '/api/public/meta/data-deletion'
      path: '/api/public/meta/data-deletion'
      fullPath: '/api/public/meta/data-deletion'
      preLoaderRoute: typeof ApiPublicMetaDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/deauthorize': {
      id: '/api/public/meta/deauthorize'
      path: '/api/public/meta/deauthorize'
      fullPath: '/api/public/meta/deauthorize'
      preLoaderRoute: typeof ApiPublicMetaDeauthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  ArmazenamentoRoute: ArmazenamentoRoute,
  BibliotecaRoute: BibliotecaRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  FotosRoute: FotosRoute,
  IntegracoesRoute: IntegracoesRoute,
  LimparIaRoute: LimparIaRoute,
  LiveRoute: LiveRoute,
  McpRoute: McpRoute,
  MetricasRoute: MetricasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  VendasRoute: VendasRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCleanerCallbackRoute: ApiPublicCleanerCallbackRoute,
  ApiPublicCleanerUploadRoute: ApiPublicCleanerUploadRoute,
  ApiPublicHlsProxyRoute: ApiPublicHlsProxyRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicRenderHookRoute: ApiPublicRenderHookRoute,
  ApiPublicRenderUploadRoute: ApiPublicRenderUploadRoute,
  IntegracoesFacebookCallbackRoute: IntegracoesFacebookCallbackRoute,
  IntegracoesInstagramCallbackRoute: IntegracoesInstagramCallbackRoute,
  IntegracoesTiktokCallbackRoute: IntegracoesTiktokCallbackRoute,
  IntegracoesYoutubeCallbackRoute: IntegracoesYoutubeCallbackRoute,
  ApiPublicHooksPublishDueRoute: ApiPublicHooksPublishDueRoute,
  ApiPublicMetaDataDeletionRoute: ApiPublicMetaDataDeletionRoute,
  ApiPublicMetaDeauthorizeRoute: ApiPublicMetaDeauthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
